# Generated by Django 4.2.2 on 2023-06-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='localizacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
