# Generated by Django 4.2.2 on 2023-06-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='DataAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(max_length=31)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.horaagendamento')),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.dataagendamento'),
        ),
    ]
