# Generated by Django 4.2.2 on 2023-06-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_horaagendamento_dataagendamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataagendamento',
            name='horario',
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.dataagendamento'),
            preserve_default=False,
        ),
    ]
