# Generated by Django 4.2.2 on 2023-06-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_rename_data_horaagendamento_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataagendamento',
            name='data',
            field=models.CharField(max_length=2),
        ),
    ]
