# Generated by Django 4.2.2 on 2023-06-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_rename_data_id_horaagendamento_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaagendamento',
            name='descricao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
