# Generated by Django 4.2.2 on 2023-06-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_horaagendamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataagendamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='horaagendamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
