# Generated by Django 4.2.2 on 2023-06-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0009_dataagendamento_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaagendamento',
            name='data',
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horaagendamento',
            name='horario9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataagendamento',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.horaagendamento'),
        ),
        migrations.AlterField(
            model_name='horaagendamento',
            name='horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
