# Generated by Django 4.2.2 on 2023-06-29 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0010_remove_horaagendamento_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataagendamento',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.horaagendamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataagendamento',
            name='data',
            field=models.CharField(max_length=50),
        ),
    ]
