# Generated by Django 4.2.2 on 2023-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0012_remove_horaagendamento_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HoraAgendamento',
        ),
    ]
