# Generated by Django 4.2.2 on 2023-06-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0016_dataagendamento_horario10_dataagendamento_horario2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectday',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
