# Generated by Django 4.2.2 on 2023-06-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0017_selectday_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectday',
            name='data_agendada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.dataagendamento'),
            preserve_default=False,
        ),
    ]
