# Generated by Django 4.2.2 on 2023-07-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0018_selectday_data_agendada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectHorarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_agendada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.dataagendamento')),
            ],
        ),
    ]
