# Generated by Django 4.2.2 on 2023-06-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotomaquiagens',
            old_name='maquiagem',
            new_name='make',
        ),
    ]
