# Generated by Django 4.2.2 on 2023-06-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_rename_maquiagem_fotomaquiagens_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotomaquiagens',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='fotos_makes'),
        ),
    ]
