# Generated by Django 4.2.2 on 2023-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
    ]
