# Generated by Django 4.2.2 on 2023-06-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='img',
        ),
        migrations.CreateModel(
            name='ImgUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='fotos_perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
        ),
    ]
