# Generated by Django 4.2.2 on 2023-06-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_img_imgusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgusuario',
            old_name='usuario',
            new_name='img_user',
        ),
    ]
